from __future__ import annotations

import os
from typing import Any

from opentelemetry import context as otel_context
from opentelemetry import trace
from opentelemetry.propagate import extract
from opentelemetry.trace import SpanKind, Status, StatusCode
from starlette.datastructures import Headers
from starlette.types import ASGIApp, Message, Receive, Scope, Send

from .telemetry import get_tracer


class OpenTelemetryASGIMiddleware:
    """Minimal framework-independent HTTP server instrumentation.

    Must be installed OUTSIDE RequestContextMiddleware so the SERVER span
    wraps the whole request lifecycle. X-Request-ID (either the inbound
    header or the one generated by RequestContextMiddleware and echoed in
    the response headers) is recorded as a span attribute.
    """

    def __init__(self, app: ASGIApp) -> None:
        self.app = app
        self.tracer = get_tracer(__name__)
        excluded = os.getenv("MAP_OTEL_EXCLUDED_PATHS", "/health,/metrics")
        self.excluded_paths = {
            path.strip() for path in excluded.split(",") if path.strip()
        }

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        headers = Headers(scope=scope)
        carrier = {key: value for key, value in headers.items()}
        parent_context = extract(carrier)
        method = str(scope.get("method") or "")
        path = str(scope.get("path") or "")
        if path in self.excluded_paths:
            await self.app(scope, receive, send)
            return
        server = scope.get("server")
        client = scope.get("client")
        attributes: dict[str, Any] = {
            "http.request.method": method,
            "url.path": path,
            "url.scheme": str(scope.get("scheme") or ""),
            "openinference.span.kind": "CHAIN",
        }
        inbound_request_id = headers.get("x-request-id")
        if inbound_request_id:
            attributes["map.request_id"] = inbound_request_id
        if isinstance(server, tuple) and server:
            attributes["server.address"] = str(server[0])
            if len(server) > 1 and server[1] is not None:
                attributes["server.port"] = int(server[1])
        if isinstance(client, tuple) and client:
            attributes["client.address"] = str(client[0])

        response_status = 500
        span = self.tracer.start_span(
            f"{method} {path}",
            context=parent_context,
            kind=SpanKind.SERVER,
            attributes=attributes,
        )
        token = otel_context.attach(
            trace.set_span_in_context(span, parent_context)
        )

        async def send_with_status(message: Message) -> None:
            nonlocal response_status
            if message["type"] == "http.response.start":
                response_status = int(message["status"])
                response_headers = Headers(
                    raw=[
                        (bytes(key), bytes(value))
                        for key, value in message.get("headers", [])
                    ]
                )
                request_id = response_headers.get("x-request-id") or (
                    inbound_request_id
                )
                if request_id:
                    span.set_attribute("map.request_id", request_id)
                session_id = response_headers.get("x-session-id")
                if session_id:
                    span.set_attribute("map.session_id", session_id)
            await send(message)

        try:
            await self.app(scope, receive, send_with_status)
        except BaseException as exc:
            span.record_exception(exc)
            span.set_status(Status(StatusCode.ERROR))
            raise
        finally:
            span.set_attribute(
                "http.response.status_code",
                response_status,
            )
            if response_status >= 500:
                span.set_status(Status(StatusCode.ERROR))
            otel_context.detach(token)
            span.end()
