"""Identity primitives (F-04).

Business services must depend only on :class:`RequestPrincipal` and never
read arbitrary headers. Internal calls use :class:`ServicePrincipal` and
cannot masquerade as a user principal.
"""

from __future__ import annotations

import enum
import re
import uuid
from dataclasses import dataclass, field

# Shared ID validation contract (mirrored by map_core): non-empty,
# <=128 chars, restricted charset. Illegal values must be ignored and a
# fresh value generated by the owning side.
_ID_RE = re.compile(r"^[A-Za-z0-9._:\-]{1,128}$")


class AuthMode(str, enum.Enum):
    DEV = "dev"
    TRUSTED_HEADER = "trusted_header"
    OIDC = "oidc"


@dataclass(frozen=True)
class RequestPrincipal:
    """Trusted caller identity resolved by the auth dependency."""

    subject: str
    user_id: str
    staff_code: str | None
    display_name: str
    roles: tuple[str, ...] = field(default_factory=tuple)
    department_code: str | None = None
    workspace_id: str = "default"
    auth_mode: AuthMode = AuthMode.DEV


@dataclass(frozen=True)
class ServicePrincipal:
    """Identity for service-to-service calls (never a user principal)."""

    service_name: str
    audience: str
    scopes: tuple[str, ...] = field(default_factory=tuple)


def is_valid_id(value: str | None) -> bool:
    return bool(value) and _ID_RE.match(value) is not None


def parse_request_id(value: str | None) -> str:
    """Accept a legal inbound request id, otherwise mint a fresh one."""
    if is_valid_id(value):
        return value  # type: ignore[return-value]
    return uuid.uuid4().hex


def parse_optional_id(value: str | None) -> str | None:
    """Accept a legal id or return None (used for session/workspace)."""
    if is_valid_id(value):
        return value  # type: ignore[return-value]
    return None


def generate_session_id() -> str:
    return uuid.uuid4().hex
