"""audit logs

Revision ID: 0627f6869560
Revises: 74ed321cc7fe
Create Date: 2026-08-09 01:30:56.771889

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0627f6869560"
down_revision = "74ed321cc7fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("before_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="map_control",
    )
    op.create_index(
        op.f("ix_map_control_audit_logs_action"),
        "audit_logs",
        ["action"],
        unique=False,
        schema="map_control",
    )
    op.create_index(
        op.f("ix_map_control_audit_logs_actor_user_id"),
        "audit_logs",
        ["actor_user_id"],
        unique=False,
        schema="map_control",
    )
    op.create_index(
        op.f("ix_map_control_audit_logs_workspace_id"),
        "audit_logs",
        ["workspace_id"],
        unique=False,
        schema="map_control",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_map_control_audit_logs_workspace_id"),
        table_name="audit_logs",
        schema="map_control",
    )
    op.drop_index(
        op.f("ix_map_control_audit_logs_actor_user_id"),
        table_name="audit_logs",
        schema="map_control",
    )
    op.drop_index(
        op.f("ix_map_control_audit_logs_action"), table_name="audit_logs", schema="map_control"
    )
    op.drop_table("audit_logs", schema="map_control")
    # ### end Alembic commands ###
