"""conversations and messages

Revision ID: 74ed321cc7fe
Revises: dfa971567a27
Create Date: 2026-08-09 01:26:36.866179

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "74ed321cc7fe"
down_revision = "dfa971567a27"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.String(length=128), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="map_control",
    )
    op.create_index(
        op.f("ix_map_control_conversations_owner_user_id"),
        "conversations",
        ["owner_user_id"],
        unique=False,
        schema="map_control",
    )
    op.create_index(
        op.f("ix_map_control_conversations_workspace_id"),
        "conversations",
        ["workspace_id"],
        unique=False,
        schema="map_control",
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("task_id", sa.String(length=128), nullable=True),
        sa.Column("decision_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("config_snapshot_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["map_control.conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.Index(
            "uq_messages_assistant_request_id",
            "request_id",
            unique=True,
            postgresql_where=sa.text("role = 'assistant' AND request_id IS NOT NULL"),
        ),
        schema="map_control",
    )
    op.create_index(
        op.f("ix_map_control_messages_conversation_id"),
        "messages",
        ["conversation_id"],
        unique=False,
        schema="map_control",
    )
    op.create_index(
        op.f("ix_map_control_messages_status"),
        "messages",
        ["status"],
        unique=False,
        schema="map_control",
    )
    op.create_table(
        "message_evidence",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("evidence_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["message_id"], ["map_control.messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", "ordinal", name="uq_message_evidence_ordinal"),
        schema="map_control",
    )
    op.create_index(
        op.f("ix_map_control_message_evidence_message_id"),
        "message_evidence",
        ["message_id"],
        unique=False,
        schema="map_control",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_map_control_message_evidence_message_id"),
        table_name="message_evidence",
        schema="map_control",
    )
    op.drop_table("message_evidence", schema="map_control")
    op.drop_index(
        op.f("ix_map_control_messages_status"), table_name="messages", schema="map_control"
    )
    op.drop_index(
        op.f("ix_map_control_messages_conversation_id"), table_name="messages", schema="map_control"
    )
    op.drop_table("messages", schema="map_control")
    op.drop_index(
        op.f("ix_map_control_conversations_workspace_id"),
        table_name="conversations",
        schema="map_control",
    )
    op.drop_index(
        op.f("ix_map_control_conversations_owner_user_id"),
        table_name="conversations",
        schema="map_control",
    )
    op.drop_table("conversations", schema="map_control")
    # ### end Alembic commands ###
