"""message feedback

Revision ID: 8ef8739dcb7c
Revises: 0627f6869560
Create Date: 2026-08-09 01:34:53.594161

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "8ef8739dcb7c"
down_revision = "0627f6869560"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_feedback",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["message_id"], ["map_control.messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", "kind", name="uq_message_feedback_message_kind"),
        schema="map_control",
    )
    op.create_index(
        op.f("ix_map_control_message_feedback_message_id"),
        "message_feedback",
        ["message_id"],
        unique=False,
        schema="map_control",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_map_control_message_feedback_message_id"),
        table_name="message_feedback",
        schema="map_control",
    )
    op.drop_table("message_feedback", schema="map_control")
    # ### end Alembic commands ###
