"""initial map_control schema

Revision ID: dfa971567a27
Revises:
Create Date: 2026-08-09 01:07:36.614585

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "dfa971567a27"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    postgresql.ENUM(
        "queued",
        "running",
        "succeeded",
        "failed",
        "cancelled",
        name="job_status",
        schema="map_control",
        create_type=False,
    )
    op.execute(
        "CREATE TYPE map_control.job_status AS ENUM "
        "('queued', 'running', 'succeeded', 'failed', 'cancelled')"
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("principal_id", sa.String(length=128), nullable=False),
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="map_control",
    )
    op.create_index(
        "uq_idempotency_scope_key",
        "idempotency_records",
        ["workspace_id", "principal_id", "key"],
        unique=True,
        schema="map_control",
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "queued",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                name="job_status",
                schema="map_control",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("idempotency_key", sa.String(length=256), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="map_control",
    )
    op.create_index(
        op.f("ix_map_control_jobs_job_type"),
        "jobs",
        ["job_type"],
        unique=False,
        schema="map_control",
    )
    op.create_index(
        op.f("ix_map_control_jobs_next_run_at"),
        "jobs",
        ["next_run_at"],
        unique=False,
        schema="map_control",
    )
    op.create_index(
        op.f("ix_map_control_jobs_status"), "jobs", ["status"], unique=False, schema="map_control"
    )
    op.create_index(
        op.f("ix_map_control_jobs_workspace_id"),
        "jobs",
        ["workspace_id"],
        unique=False,
        schema="map_control",
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="map_control",
    )
    op.create_index(
        op.f("ix_map_control_outbox_events_aggregate_id"),
        "outbox_events",
        ["aggregate_id"],
        unique=False,
        schema="map_control",
    )
    op.create_index(
        op.f("ix_map_control_outbox_events_available_at"),
        "outbox_events",
        ["available_at"],
        unique=False,
        schema="map_control",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("external_subject", sa.String(length=256), nullable=False),
        sa.Column("staff_code", sa.String(length=64), nullable=True),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("department_code", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_subject"),
        schema="map_control",
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        schema="map_control",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workspaces", schema="map_control")
    op.drop_table("users", schema="map_control")
    op.drop_index(
        op.f("ix_map_control_outbox_events_available_at"),
        table_name="outbox_events",
        schema="map_control",
    )
    op.drop_index(
        op.f("ix_map_control_outbox_events_aggregate_id"),
        table_name="outbox_events",
        schema="map_control",
    )
    op.drop_table("outbox_events", schema="map_control")
    op.drop_index(op.f("ix_map_control_jobs_workspace_id"), table_name="jobs", schema="map_control")
    op.drop_index(op.f("ix_map_control_jobs_status"), table_name="jobs", schema="map_control")
    op.drop_index(op.f("ix_map_control_jobs_next_run_at"), table_name="jobs", schema="map_control")
    op.drop_index(op.f("ix_map_control_jobs_job_type"), table_name="jobs", schema="map_control")
    op.drop_table("jobs", schema="map_control")
    op.drop_index(
        "uq_idempotency_scope_key", table_name="idempotency_records", schema="map_control"
    )
    op.drop_table("idempotency_records", schema="map_control")
    op.execute("DROP TYPE IF EXISTS map_control.job_status")
    # ### end Alembic commands ###
